name: yumyums_env3.12
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy 
  - pandas 
  - scikit-learn
  - pillow 
  - datasets
  - transformers 
  - pytorch
  - torchvision 
  - opencv
  - ipykernel 
  - accelerate
